name: Test
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Setup python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Checkout pgspot
      uses: actions/checkout@v2

    - name: Checkout pglast
      uses: actions/checkout@v2
      with:
        repository: 'svenklemm/pglast'
        submodules: true
        path: 'pglast'

    - name: Install pglast
      run: |
        python -m pip install wheel
        python -m pip install ./pglast

    - name: Run tests
      run: |
        ./test.sh

